[ids]

*
046d:b034	# bluetooth mouse

[main]

# Maps capslock to escape when pressed and control when held
capslock = layer(control)

# When the pause button is held, it skips the playing song
playpause = timeout(playpause, 500, nextsong)
